from pathlib import Path
import re,json,html
root=Path(__file__).resolve().parents[1]/'dist'
home=(root/'index.html').read_text()
origin='https://metachlorian.jezalexandersmith.chatgpt.site'
header=re.search(r'<header.*?</header>',home,re.S).group().replace('href="#','href="/#')
footer=re.search(r'<footer.*?</footer>',home,re.S).group()
favicon=re.search(r'<link rel="icon"[^>]+>',home).group()
def code(s):return '<pre><code>'+html.escape(s)+'</code></pre>'
pages=[
('self-hosted-video-library','Build a self-hosted AI video library','Keep your footage on your hardware and make individual shots searchable with Metachlorian. A practical Docker setup guide for a server or NAS.','Your footage, your infrastructure.',[
('why','Why index a library at shot level?','''<p>A folder tells you where a file lives. It rarely tells you where a specific moment is hiding. Metachlorian analyses each video as a sequence of shots and records visual meaning alongside motion, duration, speech, on-screen text and usage rights.</p><p>That lets you search for a description such as “slow coastal drone shots at golden hour” and narrow the results by the practical requirements of an edit. You can inspect why each result matched before adding it to a collection.</p>'''),
('requirements','What you need','''<p>For the Docker route, use a machine with Docker and the Docker Compose plugin, Git, and access to your footage. This can be a server, a compatible NAS or your development machine. Keep space available for the library database, downloaded models and generated media.</p><p>The default analysis models run on a CPU. A GPU is optional; it can accelerate supported models and enable richer local vision-language captions. The repository documents its CPU measurements and the limits of its evaluations.</p>'''),
('install','Start with Docker', '<p>Clone the repository, choose a long administrator password and point <code>FOOTAGE_DIR</code> at your real footage folder. Replace both example values before running:</p>'+code("git clone https://github.com/JeremySNR/Metachlorian\ncd Metachlorian\n\nMETACHLORIAN_ADMIN_PASSWORD='choose-a-long-password' \\\nFOOTAGE_DIR=/path/to/footage \\\n  docker compose -f deploy/docker-compose.yml up -d")+'''<p>Open <code>http://&lt;host&gt;:8765</code>, replacing <code>&lt;host&gt;</code> with the server address, and sign in as <code>admin</code>. On the same machine, the host can be <code>localhost</code>.</p><p>The supplied Compose configuration mounts footage read-only and keeps application data and model files in named volumes. Review that configuration when adapting it to your storage environment.</p><p>If you prefer a native installation, the repository also documents Python 3.11, uv, model downloads, the frontend build and the local server command.</p>'''),
('first-search','Make your first search useful','''<ol><li><strong>Index a representative folder.</strong> Start with footage you know so you can judge the results.</li><li><strong>Describe a moment.</strong> Include a subject, setting or remembered line rather than only a filename.</li><li><strong>Refine your requirements.</strong> Duration, shot size and intended use help narrow the selection.</li><li><strong>Inspect the evidence.</strong> Signals carry a source, confidence and model version. Correct mistakes; human corrections take priority after reprocessing.</li></ol>'''),
('rights','Add rights before handing footage off','''<p>Record the licence, permitted uses, channels, territories, expiry and releases for each file. Individual shots can override the file-level record. When you give search an intended use, Metachlorian filters against those recorded permissions.</p><p>The software helps you apply your rights records consistently. Keep those records accurate and complete: it does not independently establish ownership or obtain missing permissions.</p>'''),
('next','Take the selects into your workflow','''<p>Build collections and export through OpenTimelineIO, FCPXML or CMX 3600 EDL, or send a package to <a href="https://github.com/JeremySNR/cutawan">Cutawan</a>. If you work with AI agents, connect the same library through <a href="/guides/mcp-video-search/">Metachlorian’s MCP server</a>.</p><p>See the <a href="https://github.com/JeremySNR/Metachlorian#quick-start">repository quick start</a>, <a href="https://github.com/JeremySNR/Metachlorian/blob/HEAD/deploy/docker-compose.yml">Compose configuration</a> and <a href="https://github.com/JeremySNR/Metachlorian/tree/HEAD/eval">published evaluation</a> for the implementation details.</p>''')]),
('mcp-video-search','Connect AI agents to your video library with MCP','Connect Metachlorian to an MCP client to search footage, inspect shots, check recorded rights and prepare editing handoffs with scoped agent access.','A shared understanding of every shot.',[
('why','Let your agent search the actual archive','''<p>Metachlorian exposes the same core library to people and AI agents. Its MCP server provides tools for shot search, detailed records, transcripts, collections and rights checks. A REST API is available as well.</p><p>An agent can begin with a creative brief, find candidate footage and inspect the evidence behind a match. The response includes shot boundaries and rights verdicts, giving downstream editing tools more useful context than a filename alone.</p>'''),
('connect','Connect over HTTP','''<p>First run Metachlorian and create an agent token in <strong>Settings → Agents</strong>. Add the server to an MCP client that supports HTTP connections. The exact configuration location depends on your client; the repository provides this connection shape:</p>'''+code('''{
  "mcpServers": {
    "metachlorian": {
      "type": "http",
      "url": "http://127.0.0.1:8765/mcp/",
      "headers": {
        "Authorization": "Bearer YOUR_AGENT_TOKEN"
      }
    }
  }
}''')+'''<p>Replace the example token with the one you created. For a shared server, use its address instead of <code>127.0.0.1</code>. Treat the token as a credential and keep it out of source control.</p>'''),
('local','Or connect locally over stdio','''<p>For a client on the same machine, the CLI can run an MCP connection over standard input and output:</p>'''+code('''{
  "mcpServers": {
    "metachlorian": {
      "command": "metachlorian",
      "args": ["mcp"],
      "env": {
        "METACHLORIAN_DATA": "/path/to/library"
      }
    }
  }
}''')+'''<p>Use the path to your library and ensure the client can find the installed <code>metachlorian</code> command. Without a token, local stdio access is read-only by default.</p>'''),
('tools','Give the agent a concrete brief','''<p>Try: “Find slow coastal shots, at least eight seconds each, for a paid social edit.” A useful workflow is:</p><ol><li><code>search_shots</code> retrieves candidates using the description, filters and intended use.</li><li><code>get_shot</code> returns detailed signals, word-timed transcripts and rights information.</li><li><code>check_rights</code> evaluates the recorded permissions for the use, channel, territory and date.</li><li><code>build_package</code>, when explicitly scoped for export, prepares selected media and timelines for an editor.</li></ol><p>The agent can also scope searches to folders or collections, use <code>find_similar</code> to explore related footage and call <code>library_stats</code> to distinguish missing footage from material that has not been indexed.</p>'''),
('permissions','Keep permissions deliberate','''<p>Agents receive <code>library:read</code> access by default. Exporting media requires <code>media:export</code>; collection edits and tag corrections have separate write scopes. Rights administration and administrator scopes are not available to agent tokens.</p><p>Every agent call is audited. Agents cannot package shots unless the recorded rights verdict is <code>allowed</code>. People can review the underlying rights records in the app.</p>'''),
('next','From a brief to an editing handoff','''<p>Metachlorian handles indexing, understanding and retrieval. <a href="https://github.com/JeremySNR/cutawan">Cutawan</a> handles editing. Together, the agent can discover the relevant footage and prepare a package with media, transcripts, timelines and a rights summary.</p><p>Read the complete <a href="https://github.com/JeremySNR/Metachlorian/blob/HEAD/docs/agents.md">agent API guide</a> for exact parameters and scopes. To get the library running first, follow the <a href="/guides/self-hosted-video-library/">self-hosting guide</a>.</p>''')])]
for slug,title,description,deck,sections in pages:
 url=f'{origin}/guides/{slug}/'
 schema={'@context':'https://schema.org','@graph':[{'@type':'TechArticle','headline':title,'description':description,'url':url,'inLanguage':'en','about':{'@type':'SoftwareApplication','name':'Metachlorian'}},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Metachlorian','item':origin+'/'},{'@type':'ListItem','position':2,'name':title,'item':url}]}]}
 contents=''.join(f'<section id="{id}"><h2>{heading}</h2>{body}</section>' for id,heading,body in sections)
 toc=''.join(f'<a href="#{id}">{heading}</a>' for id,heading,_ in sections)
 document=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} | Metachlorian</title><meta name="description" content="{html.escape(description)}"><meta name="theme-color" content="#efedf7"><link rel="canonical" href="{url}"><meta property="og:type" content="article"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(description)}"><meta property="og:url" content="{url}"><meta property="og:site_name" content="Metachlorian"><meta name="twitter:card" content="summary">{favicon}<link rel="stylesheet" href="/foundations.css"><link rel="stylesheet" href="/tokens.css"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/family.css"><script defer src="/app.js"></script><script type="application/ld+json">{json.dumps(schema)}</script></head><body class="guide-page"><a class="skip-link" href="#main">Skip to content</a>{header}<main id="main"><div class="guide-hero"><a class="guide-back" href="/">Metachlorian / Guides</a><h1>{title}</h1><p>{deck}</p></div><div class="guide-layout"><aside class="guide-toc"><span>In this guide</span>{toc}</aside><article class="guide-article">{contents}<div class="guide-cta"><h2>Meet your next shot.</h2><p>Explore a sample library and see how Metachlorian puts footage in context.</p><a class="button button-wine" href="/#demo">Try the interactive demo</a></div></article></div></main>{footer}</body></html>'''
 dest=root/'guides'/slug;dest.mkdir(parents=True,exist_ok=True);(dest/'index.html').write_text(document)
urls=[origin+'/']+[f'{origin}/guides/{p[0]}/' for p in pages]
(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{url}</loc></url>\n' for url in urls)+'</urlset>\n')
(root/'robots.txt').write_text(f'User-agent: *\nAllow: /\n\nSitemap: {origin}/sitemap.xml\n')
print('Generated two complete, linked guides and crawl files.')
